Fix make separate build dir
oVirt/imgbased pull request #4
Opened 2022-02-17 18:21 UTC by didib

Fixes issue # (delete if not relevant)

## Changes introduced with this PR

*

*

*

## Are you the owner of the code you are sending in, or do you have permission of the owner?

[y/n]

2022-02-17 22:09 UTC, lveyde approved these changes

2022-02-17 22:10 UTC, lveyde approved these changes

2022-02-22 07:49 UTC, sandrobonazzola approved these changes

2022-02-22 07:51 UTC, sandrobonazzola requested changes
This is failing with:
```
install: will not overwrite just-created '/__w/imgbased/imgbased/tmp/tmp/tmp.repos/BUILDROOT/imgbased-1.2.23-1.202202220750git5049018.el8.x86_64/usr/lib/python3.6/site-packages/imgbased/constants.py' with 'src/imgbased/constants.py'
```

2022-02-23 07:02 UTC, sandrobonazzola commented
New failure:
```
RPM build errors:
make[2]: *** [Makefile:856: rpm] Error 1
make[2]: Leaving directory '/__w/imgbased/imgbased/tmp'
make[1]: *** [Makefile:873: check-build] Error 2
rm docs/imgbase.8.xml
make[1]: Leaving directory '/__w/imgbased/imgbased/tmp'
make: *** [Makefile:902: distcheck] Error 2
```

2022-02-23 07:33 UTC, didib commented
I gave up on the "do not run ./configure" patch, because it's not enough (even with slight fixes here and there). Going forward we probably do want it, and also replace autogen.sh with 'autoreconf -i' everywhere, but not urgent.

2022-02-23 09:40 UTC, sandrobonazzola approved these changes

2022-02-23 09:40 UTC, merged